### ISSUE TITLE
Empty notes show as having old data

### ISSUE THREAD

**Issue by Svagtlys** [FliegendeWurst/TriliumDroid#87]
**Describe the bug**

This is related to #79. I did the db repair before updating the TriliumDroid app to the version that fixed blob handling. However, when I open the TriliumDroid app, it now shows all empty notes as having the old data, even without editing the note, but this data does not show up on my desktop or web interfaces for TriliumNext, even after doing re-syncs across all devices, unless I first edit the note on TriliumDroid and save it. My desktop and web interfaces can correctly make new empty notes, as does TriliumDroid although it shows the old data as if it is in the note.

I uninstalled TrilumDroid and reinstalled it and still saw the issue, so I cleared the app cache and storage, re-linked it to my TriliumNext server and did a new sync, and again the old note data still shows up.

**To Reproduce**
1. Use old TriliumDroid version before blob handling was fixed
2. Create a note whose value is now set as the value for the empty blob id
3. Fix the empty blob via sql command
4. Install latest TriliumDroid version
5. Still see empty notes as having the old value that was set to the value of the empty blob id (though new notes created in TriliumDroid are truly empty even though they show this data)
 
**Expected behavior**

I would expect empty notes to not show any data, and empty notes which are edited in TriliumDroid to not add this old data to the edit field. 

**Smartphone:**
 - Device: Google Pixel 6
 - Android version: 15

**Comment by FliegendeWurst** [comment]
So the very first part is expected. As part of the update, TriliumDroid fixes the blob IDs of all the notes in its database copy. Meaning all "empty" notes now have the modified contents. It is not easy to determine where the modification really belongs to, so this was the safe option - no data lost.
I did not expect many people to have corrupted empty blobs, since it was only an issue in the first 10 minutes of the database existing. Perhaps I underestimated the amount of users who get started with Trilium using TriliumDroid, and not one of the desktop options ..

Uninstalling and reinstalling the app (without clearing data first) used to break the app completely (I did not anticipate that the database would stick around in such a case), but that was fixed in Alpha 10. The intended way to "reinstall" is to use the "delete database" button in the settings and then re-sync. Anyway, you cleared the data manually, so that's good.

The part I find really confusing is where you do a fresh sync, and yet empty notes show up differently compared to the web / desktop app. Makes me think the database got messed up in another way ...
Can you send me the database from your sync server (email in profile)? An anonymized export would also work.

**Comment by Svagtlys** [comment]
Sure I will send that database export over email.

For your second paragraph, I didn't start with Trilium using TriliumDroid, I had the desktop app, synced it to the server when I set it up, then installed TriliumDroid at least 30 minutes after setting up the server (and multiple days after setting up the desktop app), but potentially multiple days after spinning up the server instance.

**Comment by FliegendeWurst** [comment]
Got the file, thanks.

The database lists one modification to the empty blob, on 2025-04-17 08:47:07 (local time).

The database also indicates you installed Alpha 8 (with the fix) on 2025-04-21 14:08:00.
As part of the update it fixed all blob IDs. All notes that had the empty blob associated were updated to use the blob `E404LVFBd03vwqovVXWk`.

Then sometime today the app was reinstalled without deleting the database first, which seemingly synced two old changes to the sync server (not really relevant, just an observation).

So as a quick fix you can execute the SQL `UPDATE notes SET blobId = 'z4PhNX7vuL3xVChQ1m2A' WHERE blobId = 'E404LVFBd03vwqovVXWk';`
Then delete the database in TriliumDroid's settings and resync.

This will update all empty notes to use the real empty blob. Though it is still a mystery to me why the app displays something different than the desktop / web version. The database looks normal.

**Comment by Svagtlys** [comment]
I ran that sql on my desktop app, synced from it to the server, deleted the database on TriliumDroid and resynced there, and the problem is persisting. I also tried deleting the TriliumDroid database, clearing cache and storage, and setting it all back up again, but again the problem persists. Would you like another DB file sent to you?

**Comment by FliegendeWurst** [comment]
Oh, the SQL doesn't set up the sync records, you would need to run it on the database of the sync server too. Forgot to mention that, sorry.

https://sqlitebrowser.org/ is a nice tool for that.

**Comment by Svagtlys** [comment]
Is the SQL console tool in the server web ui alright as well? I ran the sql there just now and it did change things but doesn't seem to have affected the issue on droid after deleting the db and re-syncing.

**Comment by FliegendeWurst** [comment]
That should also work, yes.

Can you check the output of these two queries?

`SELECT * FROM blobs WHERE blobId = 'z4PhNX7vuL3xVChQ1m2A';`

`SELECT * FROM blobs WHERE blobId = 'E404LVFBd03vwqovVXWk';`

The first should return an empty content column. The second will have some content, most likely the text you still see in empty notes.

**Comment by FliegendeWurst** [comment]
I just realized there is one method that will almost certainly fix the database issues: you export your entire note tree, create a new blank database, and import the note tree again.
If you use Trilium's ZIP export it will preserve most metadata (labels, relations, .., but notably not revisions).

**Comment by Svagtlys** [comment]
Just to be sure before I try this, you're suggesting I follow [these export steps](https://triliumnext.github.io/Docs/Wiki/markdown.html#export), delete the database on my server and recreate a blank one, then reconnect it to trilium and import the zip file that I exported? And everything (titles, contents, relations, labels, etc) except for revision will be preserved?

**Comment by FliegendeWurst** [comment]
I would use the "HTML in ZIP archive" format, since it will preserve formatting more accurately.
Other than that your approach is correct.
You also need to make sure to export all notes at once, otherwise some relations will be lost.
(The exported ZIP contains a "!!!meta.json" file that stores relations, labels and other metadata. The actual content is stored as normal files.)

Also I would highly recommend to make another backup copy of your database beforehand, should something go wrong in the export and import.

**Comment by FliegendeWurst** [comment]
> These are the results of those sql runs on the sql console tool in the server web ui, I don't think they look exactly how you described?

Well they are certainly interesting, `[object Object]` is not what I was expecting at all. That particular value usually arises from bugs in javascript code, which my app only has very little of. The second blob apparently doesn't exist in the server's database, which is also odd. The app should have synced the new blob to the server.

**Comment by Svagtlys** [comment]
I've just followed the steps for exporting/reimporting but I'm having some potentially unrelated issues following the import. I will get back to you on the results after resolving those issues.

**Comment by Svagtlys** [comment]
So, I tried this out and had some issues with the import process (I think you saw the thread on Matrix). My notes are back, but I'm not sure that I was able to follow the instructions as you directed with the export/import due to the import-navigation pane issue. And now my TriliumDroid app is crashing often (maybe during syncs? sent the log to you through the app popup). I'm open to more suggestions on potential fixes if you have any?

**Comment by FliegendeWurst** [comment]
The crash (OutOfMemoryError) is due to a single very large note (or attachment). It will be fixed once I get around to implementing #77
